// ---- start ----
// generated by GPT-4
#[derive(Debug, Clone)]
pub enum Container {
    Blockquote,
    List {
        kind: jotdown::ListKind,
        tight: bool,
    },
    ListItem,
    TaskListItem {
        checked: bool,
    },
    DescriptionList,
    DescriptionDetails,
    Footnote {
        label: String,
    },
    Table,
    TableRow {
        head: bool,
    },
    Section {
        id: String,
    },
    Div {
        class: String,
    },
    Paragraph,
    Heading {
        level: u16,
        has_section: bool,
        id: String,
    },
    TableCell {
        alignment: jotdown::Alignment,
        head: bool,
    },
    Caption,
    DescriptionTerm,
    LinkDefinition {
        label: String,
    },
    RawBlock {
        format: String,
    },
    CodeBlock {
        language: String,
    },
    Span,
    Link(String, jotdown::LinkType),
    Image(String, jotdown::SpanLinkType),
    Verbatim,
    Math {
        display: bool,
    },
    RawInline {
        format: String,
    },
    Subscript,
    Superscript,
    Insert,
    Delete,
    Strong,
    Emphasis,
    Mark,
}

impl Container {
    pub fn from(container: &jotdown::Container) -> Self {
        match container {
            jotdown::Container::Blockquote => Self::Blockquote,
            jotdown::Container::List { kind, tight } => Self::List {
                kind: *kind,
                tight: *tight,
            },
            jotdown::Container::ListItem => Self::ListItem,
            jotdown::Container::TaskListItem { checked } => {
                Self::TaskListItem { checked: *checked }
            }
            jotdown::Container::DescriptionList => Self::DescriptionList,
            jotdown::Container::DescriptionDetails => Self::DescriptionDetails,
            jotdown::Container::Footnote { label } => Self::Footnote {
                label: label.to_string(),
            },
            jotdown::Container::Table => Self::Table,
            jotdown::Container::TableRow { head } => Self::TableRow { head: *head },
            jotdown::Container::Section { id } => Self::Section { id: id.to_string() },
            jotdown::Container::Div { class } => Self::Div {
                class: class.to_string(),
            },
            jotdown::Container::Paragraph => Self::Paragraph,
            jotdown::Container::Heading {
                level,
                has_section,
                id,
            } => Self::Heading {
                level: *level,
                has_section: *has_section,
                id: id.to_string(),
            },
            jotdown::Container::TableCell { alignment, head } => Self::TableCell {
                alignment: *alignment,
                head: *head,
            },
            jotdown::Container::Caption => Self::Caption,
            jotdown::Container::DescriptionTerm => Self::DescriptionTerm,
            jotdown::Container::LinkDefinition { label } => Self::LinkDefinition {
                label: label.to_string(),
            },
            jotdown::Container::RawBlock { format } => Self::RawBlock {
                format: format.to_string(),
            },
            jotdown::Container::CodeBlock { language } => Self::CodeBlock {
                language: language.to_string(),
            },
            jotdown::Container::Span => Self::Span,
            jotdown::Container::Link(url, link_type) => Self::Link(url.to_string(), *link_type),
            jotdown::Container::Image(url, span_link_type) => {
                Self::Image(url.to_string(), *span_link_type)
            }
            jotdown::Container::Verbatim => Self::Verbatim,
            jotdown::Container::Math { display } => Self::Math { display: *display },
            jotdown::Container::RawInline { format } => Self::RawInline {
                format: format.to_string(),
            },
            jotdown::Container::Subscript => Self::Subscript,
            jotdown::Container::Superscript => Self::Superscript,
            jotdown::Container::Insert => Self::Insert,
            jotdown::Container::Delete => Self::Delete,
            jotdown::Container::Strong => Self::Strong,
            jotdown::Container::Emphasis => Self::Emphasis,
            jotdown::Container::Mark => Self::Mark,
        }
    }
}
#[derive(Debug, Clone)]
pub enum Event {
    Str(String),
    FootnoteReference(String),
    Symbol(String),
    LeftSingleQuote,
    RightSingleQuote,
    LeftDoubleQuote,
    RightDoubleQuote,
    Ellipsis,
    EnDash,
    EmDash,
    NonBreakingSpace,
    Softbreak,
    Hardbreak,
    Escape,
    Blankline,
    ThematicBreak(Attributes),
}
impl Event {
    pub fn from(event: &jotdown::Event) -> Self {
        match event {
            jotdown::Event::Start(_, _) => unreachable!(),
            jotdown::Event::End(_) => unreachable!(),
            jotdown::Event::Str(text) => Self::Str(text.to_string()),
            jotdown::Event::FootnoteReference(label) => Self::FootnoteReference(label.to_string()),
            jotdown::Event::Symbol(symbol) => Self::Symbol(symbol.to_string()),
            jotdown::Event::LeftSingleQuote => Self::LeftSingleQuote,
            jotdown::Event::RightSingleQuote => Self::RightSingleQuote,
            jotdown::Event::LeftDoubleQuote => Self::LeftDoubleQuote,
            jotdown::Event::RightDoubleQuote => Self::RightDoubleQuote,
            jotdown::Event::Ellipsis => Self::Ellipsis,
            jotdown::Event::EnDash => Self::EnDash,
            jotdown::Event::EmDash => Self::EmDash,
            jotdown::Event::NonBreakingSpace => Self::NonBreakingSpace,
            jotdown::Event::Softbreak => Self::Softbreak,
            jotdown::Event::Hardbreak => Self::Hardbreak,
            jotdown::Event::Escape => Self::Escape,
            jotdown::Event::Blankline => Self::Blankline,
            jotdown::Event::ThematicBreak(attributes) => {
                Self::ThematicBreak(Attributes::from(attributes))
            }
        }
    }
}
// ---- end ----

#[derive(Debug, Clone)]
pub struct Attributes(Vec<(String, String)>);

impl Attributes {
    pub fn from(attributes: &jotdown::Attributes) -> Self {
        Self(
            attributes
                .iter()
                .map(|(k, v)| (k.to_string(), v.to_string()))
                .collect(),
        )
    }
}
